hub-world: world

defaults_settings:
  allow-spectator-on-death: true
  allow-tp-after-death: false

hardcore-worlds:
  hc-1:
    dimensions:
      overworld: hc-1
      nether: hc-1_nether
      end: hc-1_the_end
    settings:
      allow-spectator-on-death: true
      allow-tp-after-death: false

  hc-2:
    dimensions:
      overworld: hc-2
      nether: hc-2_nether
      end: hc-2_the_end
    settings:
      allow-spectator-on-death: false
      allow-tp-after-death: false

max-open-hardcore-worlds: 3
